#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 A Bit of Help, Inc. - Michael Gardner
"""
Configure a hybrid Alire project with the correct config.gpr.

Hybrid projects (hybrid_app_ada, hybrid_lib_ada) split their build
configuration across two files:

  config/{crate}_config.gpr  - Metadata + External build profile variable
  {crate}_shared_config.gpr  - All compiler/linker/binder switches

Alire regenerates config.gpr on every fresh `alr build` (when no
alire/ cache exists), overwriting the minimal config with a full
set of switches.  This script restores the correct hybrid config.gpr
after that initial build.

Called by brand_project.py after the first `alr build`.  Can also be
run standalone on any hybrid Alire project.

Usage:
    hybrid_configure_alire_project.py [project_dir]

If project_dir is not specified, uses the current directory.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Final

# =============================================================================
# Configuration Template - Hybrid (minimal: metadata + External only)
# =============================================================================
#
# All switches live in {crate}_shared_config.gpr, which references
# {Config}.Build_Profile for its case statement.  This config.gpr
# provides ONLY the metadata that Alire needs and the External
# variable that shared_config reads.
# =============================================================================

HYBRID_CONFIG_GPR_TEMPLATE: Final[
    str
] = '''--  Configuration for {crate_name} generated by Alire
--  Customized with optimized build profiles (development, validation, release)
--  DO NOT add [build-switches] to alire.toml - it will overwrite this file!
with "functional.gpr";
abstract project {config_name} is
   Crate_Version := "{version}";
   Crate_Name := "{crate_name}";

   Alire_Host_OS := "{host_os}";
   Alire_Host_Arch := "{host_arch}";
   Alire_Host_Distro := "{host_distro}";

   type Build_Profile_Kind is ("development", "validation", "release");
   Build_Profile : Build_Profile_Kind :=
     External ("{crate_name_upper}_BUILD_PROFILE", "development");

end {config_name};
'''


# =============================================================================
# Functions
# =============================================================================


def find_project_info(project_dir: Path) -> dict[str, str]:
    """Extract project information from existing config.gpr and alire.toml."""
    info: dict[str, str] = {
        "crate_name": "",
        "config_name": "",
        "version": "0.1.0-dev",
        "host_os": "linux",
        "host_arch": "x86_64",
        "host_distro": "ubuntu",
    }

    # Find config.gpr file
    config_dir = project_dir / "config"
    if not config_dir.exists():
        raise FileNotFoundError(
            f"The config directory was not found: {config_dir}"
        )

    config_files = list(config_dir.glob("*_config.gpr"))
    if not config_files:
        raise FileNotFoundError(
            f"No *_config.gpr file was found in {config_dir}."
        )

    config_file = config_files[0]

    # Parse existing config for values
    content = config_file.read_text()

    # Extract crate name
    match = re.search(r'Crate_Name\s*:=\s*"([^"]+)"', content)
    if match:
        info["crate_name"] = match.group(1)
        # Derive config_name from crate_name (capitalize words)
        parts = info["crate_name"].split("_")
        info["config_name"] = (
            "_".join(p.capitalize() for p in parts) + "_Config"
        )

    # Extract version
    match = re.search(r'Crate_Version\s*:=\s*"([^"]+)"', content)
    if match:
        info["version"] = match.group(1)

    # Extract host info
    match = re.search(r'Alire_Host_OS\s*:=\s*"([^"]+)"', content)
    if match:
        info["host_os"] = match.group(1)

    match = re.search(r'Alire_Host_Arch\s*:=\s*"([^"]+)"', content)
    if match:
        info["host_arch"] = match.group(1)

    match = re.search(r'Alire_Host_Distro\s*:=\s*"([^"]+)"', content)
    if match:
        info["host_distro"] = match.group(1)

    info["crate_name_upper"] = info["crate_name"].upper()

    return info


def update_config_gpr(project_dir: Path, info: dict[str, str]) -> Path:
    """Replace the config.gpr with the hybrid minimal template."""
    config_dir = project_dir / "config"
    config_file = config_dir / f"{info['crate_name']}_config.gpr"

    # Generate new content from template
    content = HYBRID_CONFIG_GPR_TEMPLATE.format(**info)

    # Write the file
    config_file.write_text(content)
    return config_file


def configure(project_dir: Path, verbose: bool = False) -> bool:
    """
    Configure a hybrid project's config.gpr.

    This is the main entry point for programmatic use (called by
    brand_project.py).

    Args:
        project_dir: Path to the project root.
        verbose: Print detailed progress.

    Returns:
        True if successful, False otherwise.
    """
    try:
        info = find_project_info(project_dir)
        if verbose:
            print(f"  Crate: {info['crate_name']}")
            print(f"  Profile variable: "
                  f"{info['crate_name_upper']}_BUILD_PROFILE")
        config_file = update_config_gpr(project_dir, info)
        if verbose:
            print(f"  Restored: {config_file}")
        return True
    except FileNotFoundError as e:
        print(f"Warning: {e}", file=sys.stderr)
        return False
    except Exception as e:
        print(f"Error configuring hybrid project: {e}", file=sys.stderr)
        return False


def main() -> int:
    """Main entry point for standalone usage."""
    parser = argparse.ArgumentParser(
        description=(
            "Configure a hybrid Alire project with the correct "
            "config.gpr."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This script restores the minimal hybrid config.gpr after Alire
regenerates it during the initial `alr build`.  Hybrid projects
keep all compiler switches in shared_config.gpr, so config.gpr
only needs metadata and the External build profile variable.

Examples:
    # After initial alr build in a freshly cloned hybrid project
    %(prog)s

    # Specify project directory
    %(prog)s /path/to/my_hybrid_project
        """,
    )
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Project directory (default: current directory)",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailed progress",
    )

    args = parser.parse_args()
    project_dir = Path(args.project_dir).resolve()

    # Validate project directory
    if not project_dir.exists():
        print(
            f"Error: The directory was not found: {project_dir}",
            file=sys.stderr,
        )
        return 1

    if not (project_dir / "alire.toml").exists():
        print(
            f"Error: This is not an Alire project "
            f"(no alire.toml): {project_dir}",
            file=sys.stderr,
        )
        return 1

    print(f"Configuring hybrid project: {project_dir}")
    if configure(project_dir, verbose=args.verbose or True):
        print("Hybrid config.gpr restored successfully.")
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(main())
