#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 A Bit of Help, Inc. - Michael Gardner
"""
Configure an Alire project with optimized build profiles.

This script replaces Alire's default config.gpr with a manually-tuned
configuration supporting development, validation, and release profiles.
It also removes any [build-switches] from alire.toml to prevent Alire
from regenerating the config.

Usage:
    configure_alire_project.py [project_dir]

If project_dir is not specified, uses the current directory.

Profiles:
    development - Debug symbols, all checks, no optimization (-O0)
    validation  - Optimized with assertions and contracts (-O2)
    release     - Maximum performance, minimal checks (-O3)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Final

# =============================================================================
# Configuration Template
# =============================================================================

CONFIG_GPR_TEMPLATE: Final[
    str
] = '''--  Configuration for {crate_name} generated by Alire
--  Customized with optimized build profiles (development, validation, release)
--  DO NOT add [build-switches] to alire.toml - it will overwrite this file!
abstract project {config_name} is
   Crate_Version := "{version}";
   Crate_Name := "{crate_name}";

   Alire_Host_OS := "{host_os}";
   Alire_Host_Arch := "{host_arch}";
   Alire_Host_Distro := "{host_distro}";

   type Build_Profile_Kind is ("development", "validation", "release");
   Build_Profile : Build_Profile_Kind :=
     External ("{crate_name_upper}_BUILD_PROFILE", "development");

   --------------------------------------------------------------------------
   --  Common flags (all profiles)
   --------------------------------------------------------------------------
   Common_Switches := (
      "-gnat2022"        --  Ada 2022 mode
     ,"-gnatf"           --  Full error messages
     ,"-gnatW8"          --  UTF-8 encoding for wide characters
   );

   --------------------------------------------------------------------------
   --  Warnings (all profiles)
   --------------------------------------------------------------------------
   Warning_Switches := (
      "-gnatwa"          --  All standard warnings
     ,"-gnatw.k"         --  Warn: variable could be constant
     ,"-gnatw.m"         --  Warn: variable assigned but never read
     ,"-gnatw.o"         --  Warn: modified but unreferenced out parameters
     ,"-gnatw.r"         --  Warn: redundant constructs
     ,"-gnatw.u"         --  Warn: unreferenced entities
     ,"-gnatw.X"         --  Suppress: local exception propagation warnings
     ,"-gnatw.Y"         --  Suppress: warnings from system units
   );

   --------------------------------------------------------------------------
   --  Style (all profiles)
   --------------------------------------------------------------------------
   Style_Switches := (
      "-gnatyy"          --  Default style (3abcefhiklmnprst)
     ,"-gnatyM79"        --  Max line length 79 characters
     ,"-gnatyA"          --  Array index numbers in attributes
     ,"-gnatyB"          --  Boolean operators (and/or vs and then/or else)
     ,"-gnatyI"          --  Explicit IN mode on parameters
     ,"-gnatyN"          --  Casing of predefined identifiers
     ,"-gnatyO"          --  Explicit overriding keywords required
     ,"-gnatyS"          --  No statements after THEN/ELSE
     ,"-gnatyu"          --  No unnecessary blank lines
     ,"-gnatyx"          --  No extra parentheses
     ,"-gnaty-s"         --  Disable: spec requirement (for simple demos)
   );

   --------------------------------------------------------------------------
   --  Profile-specific flags
   --------------------------------------------------------------------------
   Profile_Switches := ();
   case Build_Profile is
      when "development" =>
         --  Maximum debuggability, all runtime checks
         Profile_Switches := (
            "-O0"           --  No optimization (debuggable code)
           ,"-g"            --  Debug symbols
           ,"-gnata"        --  Assertions and contracts enabled
           ,"-gnato"        --  Overflow checking
           ,"-gnatVa"       --  All validity checks
           ,"-gnatE"        --  Dynamic elaboration checking
           ,"-gnateE"       --  Extra exception info in tracebacks
         );

      when "validation" =>
         --  Optimized but with assertions and debug info for testing
         Profile_Switches := (
            "-O2"           --  Optimize with debuggability
           ,"-g"            --  Debug symbols (for profiling/coverage)
           ,"-gnata"        --  Assertions and contracts enabled
           ,"-gnato"        --  Overflow checking
           ,"-gnatVa"       --  All validity checks
         );

      when "release" =>
         --  Maximum performance, minimal runtime overhead
         Profile_Switches := (
            "-O3"           --  Maximum optimization
           ,"-gnatn"        --  Enable inlining
           ,"-gnatp"        --  Suppress all checks (use with caution!)
           ,"-fdata-sections"
           ,"-ffunction-sections"
         );
   end case;

   --------------------------------------------------------------------------
   --  Combined switches
   --------------------------------------------------------------------------
   Ada_Compiler_Switches :=
     External_As_List ("ADAFLAGS", " ")
     & Common_Switches
     & Warning_Switches
     & Style_Switches
     & Profile_Switches;

end {config_name};
'''

ALIRE_TOML_COMMENT: Final[
    str
] = '''
# =============================================================================
# BUILD CONFIGURATION POLICY
# =============================================================================
#
# IMPORTANT: Do NOT add [build-switches] to this file!
#
# Why?
# ----
# 1. Alire's [build-switches] regenerates config/{crate_name}_config.gpr,
#    overwriting any manual customizations.
#
# 2. The .gpr file supports advanced features that alire.toml cannot express:
#    - Multiple build profiles (development, validation, release)
#    - Case expressions for profile-specific flags
#    - Fine-grained control over warnings, style, and runtime checks
#
# 3. Our config/{crate_name}_config.gpr has been manually tuned with:
#    - development: -O0, -g, -gnata, -gnato, -gnatVa, -gnatE, -gnateE
#    - validation:  -O2, -g, -gnata, -gnato, -gnatVa (optimized + contracts)
#    - release:     -O3, -gnatn, -gnatp (maximum performance)
#
# How to Build
# ------------
# Always use gprbuild directly, or via Alire's exec wrapper:
#
#   # Development (default)
#   alr exec -- gprbuild -P {crate_name}.gpr
#
#   # Validation (optimized with assertions)
#   alr exec -- gprbuild -P {crate_name}.gpr -X{crate_name_upper}_BUILD_PROFILE=validation
#
#   # Release (production)
#   alr exec -- gprbuild -P {crate_name}.gpr -X{crate_name_upper}_BUILD_PROFILE=release
#
# GNAT Studio with Alire integration also uses gprbuild directly, so the
# custom .gpr configuration is honored.
#
# WARNING: Running `alr build` directly (not `alr exec -- gprbuild`) may
# regenerate the config.gpr if [build-switches] is ever added here.
# =============================================================================
'''


# =============================================================================
# Functions
# =============================================================================


def find_project_info(project_dir: Path) -> dict[str, str]:
    """Extract project information from existing config.gpr and alire.toml."""
    info: dict[str, str] = {
        "crate_name": "",
        "config_name": "",
        "version": "0.1.0-dev",
        "host_os": "macos",
        "host_arch": "x86_64",
        "host_distro": "homebrew",
    }

    # Find config.gpr file
    config_dir = project_dir / "config"
    if not config_dir.exists():
        raise FileNotFoundError(f"Config directory not found: {config_dir}")

    config_files = list(config_dir.glob("*_config.gpr"))
    if not config_files:
        raise FileNotFoundError(f"No *_config.gpr file found in {config_dir}")

    config_file = config_files[0]
    info["config_name"] = config_file.stem.replace("_config", "_Config")

    # Parse existing config for values
    content = config_file.read_text()

    # Extract crate name
    match = re.search(r'Crate_Name\s*:=\s*"([^"]+)"', content)
    if match:
        info["crate_name"] = match.group(1)
        # Derive config_name from crate_name (capitalize words)
        parts = info["crate_name"].split("_")
        info["config_name"] = "_".join(p.capitalize() for p in parts) + "_Config"

    # Extract version
    match = re.search(r'Crate_Version\s*:=\s*"([^"]+)"', content)
    if match:
        info["version"] = match.group(1)

    # Extract host info
    match = re.search(r'Alire_Host_OS\s*:=\s*"([^"]+)"', content)
    if match:
        info["host_os"] = match.group(1)

    match = re.search(r'Alire_Host_Arch\s*:=\s*"([^"]+)"', content)
    if match:
        info["host_arch"] = match.group(1)

    match = re.search(r'Alire_Host_Distro\s*:=\s*"([^"]+)"', content)
    if match:
        info["host_distro"] = match.group(1)

    info["crate_name_upper"] = info["crate_name"].upper()

    return info


def update_config_gpr(project_dir: Path, info: dict[str, str]) -> Path:
    """Replace the config.gpr with our optimized template."""
    config_dir = project_dir / "config"
    config_file = config_dir / f"{info['crate_name']}_config.gpr"

    # Generate new content from template
    content = CONFIG_GPR_TEMPLATE.format(**info)

    # Write the file
    config_file.write_text(content)
    return config_file


def clean_alire_toml(project_dir: Path, info: dict[str, str]) -> Path:
    """Remove [build-switches] and add policy comment to alire.toml."""
    alire_file = project_dir / "alire.toml"
    if not alire_file.exists():
        raise FileNotFoundError(f"alire.toml not found: {alire_file}")

    content = alire_file.read_text()
    original_content = content

    # Remove [build-switches] section (and any subsections like [build-switches.*])
    # This regex matches the section header and everything until the next section
    # or end of file
    content = re.sub(
        r'\n*\[build-switches[^\]]*\][^\[]*',
        '',
        content,
        flags=re.MULTILINE
    )

    # Remove [gpr-set-externals] section if it only contains build profile stuff
    content = re.sub(
        r'\n*\[gpr-set-externals\][^\[]*',
        '',
        content,
        flags=re.MULTILINE
    )

    # Remove any existing BUILD CONFIGURATION POLICY comment block
    content = re.sub(
        r'\n*# =+\n# BUILD CONFIGURATION POLICY\n# =+.*?# =+\n*',
        '',
        content,
        flags=re.DOTALL
    )

    # Ensure file ends with newline, then add our comment block
    content = content.rstrip() + "\n"
    content += ALIRE_TOML_COMMENT.format(**info)

    # Only write if changed
    if content != original_content:
        alire_file.write_text(content)

    return alire_file


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Configure an Alire project with optimized build profiles.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Configure current directory
    %(prog)s

    # Configure specific project
    %(prog)s /path/to/my_project

    # After running alr init
    alr init --bin my_app
    cd my_app
    %(prog)s
        """,
    )
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Project directory (default: current directory)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes",
    )

    args = parser.parse_args()
    project_dir = Path(args.project_dir).resolve()

    # Validate project directory
    if not project_dir.exists():
        print(f"Error: Directory not found: {project_dir}", file=sys.stderr)
        return 1

    if not (project_dir / "alire.toml").exists():
        print(f"Error: Not an Alire project (no alire.toml): {project_dir}",
              file=sys.stderr)
        return 1

    try:
        # Extract project info
        print(f"Analyzing project: {project_dir}")
        info = find_project_info(project_dir)
        print(f"  Crate name: {info['crate_name']}")
        print(f"  Version: {info['version']}")
        print(f"  Build profile variable: {info['crate_name_upper']}_BUILD_PROFILE")

        if args.dry_run:
            print("\n[DRY RUN] Would update:")
            print(f"  - config/{info['crate_name']}_config.gpr")
            print(f"  - alire.toml")
            return 0

        # Update config.gpr
        config_file = update_config_gpr(project_dir, info)
        print(f"\nUpdated: {config_file}")

        # Clean alire.toml
        alire_file = clean_alire_toml(project_dir, info)
        print(f"Updated: {alire_file}")

        # Print usage
        print("\nBuild profiles configured:")
        print(f"  Development: alr exec -- gprbuild -P {info['crate_name']}.gpr")
        print(f"  Validation:  alr exec -- gprbuild -P {info['crate_name']}.gpr "
              f"-X{info['crate_name_upper']}_BUILD_PROFILE=validation")
        print(f"  Release:     alr exec -- gprbuild -P {info['crate_name']}.gpr "
              f"-X{info['crate_name_upper']}_BUILD_PROFILE=release")

        return 0

    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
